version: '3.8'

services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - node_network

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    networks:
      - node_network

networks:
  node_network:
    driver: bridge
